skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ptrans = "FbXJSZ171dcnHJVrd5E6KwvXAx7bMgxC44McF84vJ6cK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
